"""calendar events

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-27 09:50:34.782113

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=15), server_default='personal', nullable=False),
    sa.Column('category', sa.String(length=15), server_default='personal', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('recurrence', sa.String(length=10), nullable=True),
    sa.Column('anchor_day', sa.Integer(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('reminder_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('personal', 'work', 'health', 'family', 'finance', 'education', 'social', 'travel', 'other')", name=op.f('ck_calendar_events_category_valid')),
    sa.CheckConstraint("event_type IN ('appointment', 'personal', 'deadline')", name=op.f('ck_calendar_events_event_type_valid')),
    sa.CheckConstraint("recurrence IS NULL OR recurrence IN ('daily', 'weekly', 'monthly', 'yearly')", name=op.f('ck_calendar_events_recurrence_valid')),
    sa.CheckConstraint('anchor_day BETWEEN 1 AND 31', name=op.f('ck_calendar_events_anchor_day_range')),
    sa.CheckConstraint('char_length(btrim(title)) BETWEEN 1 AND 200', name=op.f('ck_calendar_events_title_length')),
    sa.CheckConstraint('description IS NULL OR char_length(description) <= 2000', name=op.f('ck_calendar_events_description_length')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_calendar_events_end_after_start')),
    sa.CheckConstraint('end_time IS NULL OR end_date > start_date OR end_time >= start_time', name=op.f('ck_calendar_events_end_time_after_start_time')),
    sa.CheckConstraint('end_time IS NULL OR start_time IS NOT NULL', name=op.f('ck_calendar_events_end_time_needs_start_time')),
    sa.CheckConstraint('reminder_minutes IS NULL OR reminder_minutes IN (0, 5, 10, 15, 30, 60, 120, 1440, 2880, 10080)', name=op.f('ck_calendar_events_reminder_minutes_valid')),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], name=op.f('fk_calendar_events_reminder_id_reminders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events'))
    )
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_index('ix_calendar_events_user_id_start_date', 'calendar_events', ['user_id', 'start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_calendar_events_user_id_start_date', table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
