"""tasks and reminders

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-24 20:54:39.664014

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repeat', sa.String(length=10), server_default='none', nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=True),
    sa.Column('interval_unit', sa.String(length=10), nullable=True),
    sa.Column('anchor_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(repeat = 'custom' AND interval_count BETWEEN 1 AND 365 AND interval_unit IN ('days', 'weeks', 'months', 'years')) OR (repeat <> 'custom' AND interval_count IS NULL AND interval_unit IS NULL)", name=op.f('ck_reminders_custom_interval_consistent')),
    sa.CheckConstraint("repeat IN ('none', 'daily', 'weekly', 'monthly', 'yearly', 'custom')", name=op.f('ck_reminders_repeat_valid')),
    sa.CheckConstraint("status = 'active' OR repeat = 'none'", name=op.f('ck_reminders_only_one_time_completes')),
    sa.CheckConstraint("status IN ('active', 'completed')", name=op.f('ck_reminders_status_valid')),
    sa.CheckConstraint('char_length(btrim(title)) BETWEEN 1 AND 200', name=op.f('ck_reminders_title_length')),
    sa.CheckConstraint('notes IS NULL OR char_length(notes) <= 2000', name=op.f('ck_reminders_notes_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_index('ix_reminders_user_id_remind_at', 'reminders', ['user_id', 'remind_at'], unique=False)
    op.create_table('tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=10), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=15), server_default='not_started', nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('recurrence', sa.String(length=10), nullable=True),
    sa.Column('anchor_day', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_task_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'completed') = (completed_at IS NOT NULL)", name=op.f('ck_tasks_completed_at_consistent')),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'urgent')", name=op.f('ck_tasks_priority_valid')),
    sa.CheckConstraint("recurrence IS NULL OR recurrence IN ('daily', 'weekly', 'monthly', 'yearly')", name=op.f('ck_tasks_recurrence_valid')),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'completed', 'cancelled')", name=op.f('ck_tasks_status_valid')),
    sa.CheckConstraint('char_length(btrim(title)) BETWEEN 1 AND 200', name=op.f('ck_tasks_title_length')),
    sa.CheckConstraint('description IS NULL OR char_length(description) <= 5000', name=op.f('ck_tasks_description_length')),
    sa.CheckConstraint('due_time IS NULL OR due_date IS NOT NULL', name=op.f('ck_tasks_time_needs_date')),
    sa.CheckConstraint('recurrence IS NULL OR due_date IS NOT NULL', name=op.f('ck_tasks_recurrence_needs_date')),
    sa.ForeignKeyConstraint(['previous_task_id'], ['tasks.id'], name=op.f('fk_tasks_previous_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index('ix_tasks_user_id_status_due_date', 'tasks', ['user_id', 'status', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_id_status_due_date', table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_reminders_user_id_remind_at', table_name='reminders')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
