"""categories incomes and expenses

Adds income/expense records (NUMERIC(14,2) amounts) and categories, and seeds the
built-in income and expense categories.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-24 12:30:33.219320

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

INCOME_CATEGORIES = [
    ("salary", "Salary"), ("freelance", "Freelance"), ("business", "Business"), ("allowance", "Allowance"),
    ("investment", "Investment"), ("gift", "Gift"), ("other", "Other"),
]
EXPENSE_CATEGORIES = [
    ("rent", "Rent"), ("food", "Food"), ("groceries", "Groceries"), ("electricity", "Electricity"),
    ("water", "Water"), ("internet", "Internet/Wi-Fi"), ("mobile", "Mobile"), ("transportation", "Transportation"),
    ("fuel", "Fuel"), ("education", "Education"), ("medical", "Medical"), ("shopping", "Shopping"),
    ("clothing", "Clothing"), ("entertainment", "Entertainment"), ("subscription", "Subscription"),
    ("travel", "Travel"), ("family", "Family"), ("personal_care", "Personal Care"), ("household", "Household"),
    ("loan_payment", "Loan Payment"), ("insurance", "Insurance"), ("other", "Other"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('income', 'expense')", name=op.f('ck_categories_kind_valid')),
    sa.CheckConstraint('(is_system AND user_id IS NULL) OR (NOT is_system AND user_id IS NOT NULL)', name=op.f('ck_categories_owner_consistent')),
    sa.CheckConstraint('char_length(btrim(name)) BETWEEN 1 AND 50', name=op.f('ck_categories_name_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_index('uq_categories_system_kind_name', 'categories', ['kind', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('uq_categories_user_kind_name', 'categories', ['user_id', 'kind', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))

    # Built-in categories (frozen copy: migrations must not depend on app code that may change).
    categories = sa.table(
        "categories",
        sa.column("kind", sa.String),
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
        sa.column("is_system", sa.Boolean),
    )
    op.bulk_insert(
        categories,
        [{"kind": "income", "slug": slug, "name": name, "is_system": True} for slug, name in INCOME_CATEGORIES]
        + [{"kind": "expense", "slug": slug, "name": name, "is_system": True} for slug, name in EXPENSE_CATEGORIES],
    )

    op.create_table('expenses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NPR', nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recurrence_interval', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(is_recurring AND recurrence_interval IN ('weekly', 'monthly', 'quarterly', 'yearly')) OR (NOT is_recurring AND recurrence_interval IS NULL)", name=op.f('ck_expenses_recurrence_consistent')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_expenses_currency_code')),
    sa.CheckConstraint("payment_method IN ('cash', 'bank_transfer', 'card', 'mobile_wallet', 'cheque', 'other')", name=op.f('ck_expenses_payment_method_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_amount_positive')),
    sa.CheckConstraint('notes IS NULL OR char_length(notes) <= 2000', name=op.f('ck_expenses_notes_length')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_expenses_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expenses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index('ix_expenses_user_id_date', 'expenses', ['user_id', 'date'], unique=False)
    op.create_table('incomes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NPR', nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recurrence_interval', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(is_recurring AND recurrence_interval IN ('weekly', 'monthly', 'quarterly', 'yearly')) OR (NOT is_recurring AND recurrence_interval IS NULL)", name=op.f('ck_incomes_recurrence_consistent')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_incomes_currency_code')),
    sa.CheckConstraint("payment_method IN ('cash', 'bank_transfer', 'card', 'mobile_wallet', 'cheque', 'other')", name=op.f('ck_incomes_payment_method_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_incomes_amount_positive')),
    sa.CheckConstraint('notes IS NULL OR char_length(notes) <= 2000', name=op.f('ck_incomes_notes_length')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_incomes_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_incomes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incomes'))
    )
    op.create_index(op.f('ix_incomes_category_id'), 'incomes', ['category_id'], unique=False)
    op.create_index('ix_incomes_user_id_date', 'incomes', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incomes_user_id_date', table_name='incomes')
    op.drop_index(op.f('ix_incomes_category_id'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index('ix_expenses_user_id_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('uq_categories_user_kind_name', table_name='categories', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_categories_system_kind_name', table_name='categories', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
