"""account settings and security activity

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-27 11:56:57.344701

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_activity',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("event IN ('login_succeeded', 'login_failed', 'logout', 'password_changed', 'password_reset', 'session_revoked', 'other_sessions_revoked', 'profile_updated', 'email_changed', 'username_changed', 'data_exported')", name=op.f('ck_security_activity_event_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_security_activity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_activity'))
    )
    op.create_index('ix_security_activity_user_id_created_at', 'security_activity', ['user_id', 'created_at'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NPR', nullable=False),
    sa.Column('date_format', sa.String(length=10), server_default='default', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_user_preferences_currency_code')),
    sa.CheckConstraint("date_format IN ('default', 'dmy', 'mdy', 'iso')", name=op.f('ck_user_preferences_date_format_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_preferences'))
    )
    op.create_index('ix_bill_payments_user_id_paid_on', 'bill_payments', ['user_id', 'paid_on'], unique=False)
    op.add_column('users', sa.Column('avatar_key', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('avatar_content_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('avatar_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_updated_at')
    op.drop_column('users', 'avatar_content_type')
    op.drop_column('users', 'avatar_key')
    op.drop_index('ix_bill_payments_user_id_paid_on', table_name='bill_payments')
    op.drop_table('user_preferences')
    op.drop_index('ix_security_activity_user_id_created_at', table_name='security_activity')
    op.drop_table('security_activity')
    # ### end Alembic commands ###
