"""notes and documents

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-26 09:30:13.571678

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_kind', sa.String(length=10), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('identity', 'education', 'finance', 'medical', 'property', 'insurance', 'work', 'receipts', 'personal', 'other')", name=op.f('ck_documents_category_valid')),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_documents_sha256_format')),
    sa.CheckConstraint('char_length(btrim(title)) BETWEEN 1 AND 200', name=op.f('ck_documents_title_length')),
    sa.CheckConstraint('description IS NULL OR char_length(description) <= 2000', name=op.f('ck_documents_description_length')),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_documents_size_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_index('ix_documents_user_id_created_at', 'documents', ['user_id', 'created_at'], unique=False)
    op.create_table('notes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.String(length=15), server_default='personal', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=30)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('personal', 'work', 'education', 'finance', 'ideas', 'important', 'other')", name=op.f('ck_notes_category_valid')),
    sa.CheckConstraint('NOT (is_archived AND is_pinned)', name=op.f('ck_notes_archived_not_pinned')),
    sa.CheckConstraint('cardinality(tags) <= 20', name=op.f('ck_notes_tag_count')),
    sa.CheckConstraint('char_length(btrim(title)) BETWEEN 1 AND 200', name=op.f('ck_notes_title_length')),
    sa.CheckConstraint('char_length(content) <= 100000', name=op.f('ck_notes_content_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('ix_notes_tags', 'notes', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_index('ix_notes_user_id_updated_at', 'notes', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_user_id_updated_at', table_name='notes')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index('ix_notes_tags', table_name='notes', postgresql_using='gin')
    op.drop_table('notes')
    op.drop_index('ix_documents_user_id_created_at', table_name='documents')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
