"""password vault

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-26 09:50:31.648238

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_audit_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('entry_label', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("action IN ('entry_created', 'entry_updated', 'entry_deleted', 'secret_revealed', 'secret_copied', 'vault_unlocked', 'unlock_failed', 'vault_locked')", name=op.f('ck_vault_audit_log_action_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vault_audit_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_audit_log'))
    )
    op.create_index('ix_vault_audit_log_user_id_created_at', 'vault_audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('vault_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.String(length=20), server_default='other', nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('username_enc', sa.LargeBinary(), nullable=True),
    sa.Column('email_enc', sa.LargeBinary(), nullable=True),
    sa.Column('password_enc', sa.LargeBinary(), nullable=False),
    sa.Column('notes_enc', sa.LargeBinary(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('email', 'social_media', 'banking', 'education', 'work', 'shopping', 'government', 'hosting', 'other')", name=op.f('ck_vault_entries_category_valid')),
    sa.CheckConstraint("url IS NULL OR url ~* '^https?://'", name=op.f('ck_vault_entries_url_scheme')),
    sa.CheckConstraint('char_length(btrim(website)) BETWEEN 1 AND 200', name=op.f('ck_vault_entries_website_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vault_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_entries'))
    )
    op.create_index(op.f('ix_vault_entries_user_id'), 'vault_entries', ['user_id'], unique=False)
    op.create_index('ix_vault_entries_user_id_website', 'vault_entries', ['user_id', 'website'], unique=False)
    op.create_table('vault_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wrapped_key', sa.LargeBinary(), nullable=False),
    sa.Column('kek_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vault_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_vault_keys'))
    )
    op.add_column('user_sessions', sa.Column('vault_unlocked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'vault_unlocked_until')
    op.drop_table('vault_keys')
    op.drop_index('ix_vault_entries_user_id_website', table_name='vault_entries')
    op.drop_index(op.f('ix_vault_entries_user_id'), table_name='vault_entries')
    op.drop_table('vault_entries')
    op.drop_index('ix_vault_audit_log_user_id_created_at', table_name='vault_audit_log')
    op.drop_table('vault_audit_log')
    # ### end Alembic commands ###
