"""budgets bills and savings

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 20:23:13.522655

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NPR', nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('anchor_day', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('rent', 'wifi', 'electricity', 'water', 'mobile', 'subscription', 'insurance', 'loan', 'other')", name=op.f('ck_bills_category_valid')),
    sa.CheckConstraint("frequency IN ('one_time', 'weekly', 'monthly', 'quarterly', 'yearly')", name=op.f('ck_bills_frequency_valid')),
    sa.CheckConstraint("status IN ('pending', 'paid')", name=op.f('ck_bills_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_bills_amount_positive')),
    sa.CheckConstraint('anchor_day BETWEEN 1 AND 31', name=op.f('ck_bills_anchor_day_range')),
    sa.CheckConstraint('notes IS NULL OR char_length(notes) <= 2000', name=op.f('ck_bills_notes_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bills'))
    )
    op.create_index(op.f('ix_bills_user_id'), 'bills', ['user_id'], unique=False)
    op.create_index('ix_bills_user_id_due_date', 'bills', ['user_id', 'due_date'], unique=False)
    op.create_table('savings_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NPR', nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_amount >= 0', name=op.f('ck_savings_goals_current_non_negative')),
    sa.CheckConstraint('description IS NULL OR char_length(description) <= 2000', name=op.f('ck_savings_goals_description_length')),
    sa.CheckConstraint('target_amount > 0', name=op.f('ck_savings_goals_target_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_savings_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_savings_goals'))
    )
    op.create_index(op.f('ix_savings_goals_user_id'), 'savings_goals', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('warning_threshold', sa.Integer(), server_default='80', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_budgets_amount_positive')),
    sa.CheckConstraint('extract(day from month) = 1', name=op.f('ck_budgets_month_first_day')),
    sa.CheckConstraint('warning_threshold BETWEEN 1 AND 100', name=op.f('ck_budgets_threshold_range')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_budgets_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budgets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('user_id', 'category_id', 'month', name='uq_budgets_user_category_month')
    )
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('savings_contributions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_savings_contributions_amount_non_zero')),
    sa.ForeignKeyConstraint(['goal_id'], ['savings_goals.id'], name=op.f('fk_savings_contributions_goal_id_savings_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_savings_contributions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_savings_contributions'))
    )
    op.create_index(op.f('ix_savings_contributions_goal_id'), 'savings_contributions', ['goal_id'], unique=False)
    op.create_index('ix_savings_contributions_user_id_date', 'savings_contributions', ['user_id', 'date'], unique=False)
    op.create_table('bill_payments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_bill_payments_amount_positive')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_payments_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_bill_payments_expense_id_expenses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bill_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_payments'))
    )
    op.create_index(op.f('ix_bill_payments_bill_id'), 'bill_payments', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_payments_user_id'), 'bill_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_payments_user_id'), table_name='bill_payments')
    op.drop_index(op.f('ix_bill_payments_bill_id'), table_name='bill_payments')
    op.drop_table('bill_payments')
    op.drop_index('ix_savings_contributions_user_id_date', table_name='savings_contributions')
    op.drop_index(op.f('ix_savings_contributions_goal_id'), table_name='savings_contributions')
    op.drop_table('savings_contributions')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_savings_goals_user_id'), table_name='savings_goals')
    op.drop_table('savings_goals')
    op.drop_index('ix_bills_user_id_due_date', table_name='bills')
    op.drop_index(op.f('ix_bills_user_id'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
