"""notifications

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-27 11:16:07.553608

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('users_checked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notifications_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'skipped')", name=op.f('ck_job_runs_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index('ix_job_runs_name_started_at', 'job_runs', ['name', 'started_at'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_overdue', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('task_upcoming', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('bill_overdue', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('bill_upcoming', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('budget_threshold', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('savings_milestone', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reminder_due', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('task_lead_days', sa.Integer(), server_default='1', nullable=False),
    sa.Column('bill_lead_days', sa.Integer(), server_default='3', nullable=False),
    sa.Column('browser_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bill_lead_days BETWEEN 0 AND 30', name=op.f('ck_notification_preferences_bill_lead_days_range')),
    sa.CheckConstraint('task_lead_days BETWEEN 0 AND 14', name=op.f('ck_notification_preferences_task_lead_days_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_notification_preferences'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_type', sa.String(length=15), nullable=False),
    sa.Column('related_id', sa.UUID(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("related_type IN ('task', 'bill', 'budget', 'savings_goal', 'reminder')", name=op.f('ck_notifications_related_type_valid')),
    sa.CheckConstraint("type IN ('task_overdue', 'task_upcoming', 'bill_overdue', 'bill_upcoming', 'budget_threshold', 'savings_milestone', 'reminder_due')", name=op.f('ck_notifications_type_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_id_unread', 'notifications', ['user_id'], unique=False, postgresql_where=sa.text('read_at IS NULL AND dismissed_at IS NULL'))
    op.create_index('uq_notifications_user_id_dedupe_key', 'notifications', ['user_id', 'dedupe_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notifications_user_id_dedupe_key', table_name='notifications')
    op.drop_index('ix_notifications_user_id_unread', table_name='notifications', postgresql_where=sa.text('read_at IS NULL AND dismissed_at IS NULL'))
    op.drop_index('ix_notifications_user_id_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_index('ix_job_runs_name_started_at', table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
